version: '3'
services:
  postgres:
    build: 
      context: ./database
      dockerfile: Dockerfile
      args:
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
    ports:
      - 54321:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
    ports:
      - 3001:3001
    restart: unless-stopped
    depends_on:
      - postgres
  frontend:
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - backend