version: '3'
services:
  postgres:
    build: 
      context: ./database
    volumes:
      - postgres-data:/volume
    restart: unless-stopped
    networks:
      - private
  backend:
    build: 
      context: ./backend
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - public
      - private
  frontend:
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - public
volumes:
  postgres-data:  
networks:
  public:
  private: